### ISSUE TITLE
HTML+CSS 

### ISSUE THREAD

**Issue by TFK70** [atls-academy/brusselboy.github.io#1]
### С чем связан запрос на фичу?

Сверстать макет - https://www.figma.com/file/Z8m03nUsEoolW0WcLMU93h/Work-project?node-id=0%3A1

### Расскажите как вы это себе видите

Использовать только чистый HTML и CSS

### Приложите примеры реализаций

https://github.com/atls-academy/tfk70.github.io/pull/5

**Comment by brusselboy** [comment]
Задача решена:

- https://github.com/atls-academy/brusselboy.github.io/pull/2
