### ISSUE TITLE
Frod Analytics

### ISSUE THREAD

**Issue by brusselboy** [atls-academy/brusselboy.github.io#12]
### С чем связан запрос на фичу?

[ref](https://github.com/YouThinkResearch/web/issues/695)

Сделать страницу анализа фрода для бэк панели

[Дизайн](https://www.figma.com/file/ofuBEflZhwVbl3eGV9EXvv/Youthink-%7C-Back-Panel?node-id=306%3A25168)

### Расскажите как вы это себе видите

**Locations:**

- `admin/pages`
- `admin/fragments`

**Роут:**

- `/frod-analytics`

**Comment by brusselboy** [comment]
## Проблема с мержем веток
@TFK70 

### Описание
Когда делаю мерж мастера в свою ветку появляются конфликты, некоторые разрешаются с помощью `yarn`, остальные остаются. Ещё обратил внимание когда обновил мастер и проинсталился, изменился файл `1655325826644-CreateAccount.ts` , не знаю должно ли так быть или нет, посчитал что написать об этом стоит.

```
git status
On the master branch
Your branch has been updated according to "origin/master".

Changes that are not in the commit index:
  (use "git add <file>..." to add the file to the index)
  (use "git restore <file>..." to undo changes in the working directory)
        Modified:      accounting/adapters/typeorm-adapter/src/migrations/1655325826644-CreateAccount.ts

no changes added for the commit
(use "git add" and/or "git commit -a")

```
### Материалы

После того как сделал `git merge master` на своей ветке, в ярн чеках следующее:

1. Format

```

➤ YN0000: ┌ Format
➤ YN0000: │ Merge conflict marker encountered. (10:1)
➤ YN0000: │    8 | import { Observable }                   from 'rxjs'
➤ YN0000: │    9 |
➤ YN0000: │ > 10 | <<<<<<< HEAD
➤ YN0000: │      | ^
➤ YN0000: │   11 | import { CreateAccountRequest }         from '../../../../team/youthink/payout/v1alpha1/account.payloads'
➤ YN0000: │   12 | import { CreateAccountResponse }        from '../../../../team/youthink/payout/v1alpha1/account.payloads'
➤ YN0000: │   13 | import { ListAccountsRequest }          from '../../../../team/youthink/payout/v1alpha1/account.payloads'
➤ YN0000: │ 
➤ YN0000: │ qe                                                                                                                                            [worker eval]:69:15383
➤ YN0000: │ UU                                                                                                                                            [worker eval]:348:5931
➤ YN0000: │ Object.zU                                                                                                                                     [worker eval]:348:6254
➤ YN0000: │ Object.preprocess                                                                                                                             [worker eval]:10776:84
➤ YN0000: │ Object.g                                                                                                                                      [worker eval]:395:1312
➤ YN0000: │ b                                                                                                                                            [worker eval]:396:14988
➤ YN0000: │ D                                                                                                                                              [worker eval]:400:580
➤ YN0000: │                                                                                                                                               [worker eval]:470:7260
➤ YN0000: │ Object.format                                                                                                                                 [worker eval]:470:7351
➤ YN0000: │ Formatter.formatFiles                                                                                                                         [worker eval]:11759:41
➤ YN0000: └ Completed in 15s 361ms
➤ YN0000: Failed with errors in 15s 363ms

```
2. Typecheck

```
➤ YN0000: ┌ Typecheck
➤ YN0000: │ .yarn/__virtual__/@payout-payout-proto-virtual-e736e62be1/1/payout/protos/payout/gen/nestjs/team/youthink/payout/v1alpha1/payout.service.ts
➤ YN0000: │ 
➤ YN0000: │   Error: Merge conflict marker encountered.
➤ YN0000: │ 
➤ YN0000: │ 
➤ YN0000: │ .yarn/__virtual__/@payout-payout-proto-virtual-e736e62be1/1/payout/protos/payout/gen/nestjs/team/youthink/payout/v1alpha1/payout.service.ts
➤ YN0000: │ 
➤ YN0000: │   Error: Merge conflict marker encountered.
➤ YN0000: │ 
➤ YN0000: │ 
➤ YN0000: │ .yarn/__virtual__/@payout-payout-proto-virtual-e736e62be1/1/payout/protos/payout/gen/nestjs/team/youthink/payout/v1alpha1/payout.service.ts
➤ YN0000: │ 
➤ YN0000: │   Error: Merge conflict marker encountered.
➤ YN0000: │ 
➤ YN0000: │ 
➤ YN0000: │ payout/protos/payout/gen/nestjs/team/youthink/payout/v1alpha1/payout.service.ts
➤ YN0000: │ 
➤ YN0000: │   Error: Merge conflict marker encountered.
➤ YN0000: │ 
➤ YN0000: │ 
➤ YN0000: │ payout/protos/payout/gen/nestjs/team/youthink/payout/v1alpha1/payout.service.ts
➤ YN0000: │ 
➤ YN0000: │   Error: Merge conflict marker encountered.
➤ YN0000: │ 
➤ YN0000: │ 
➤ YN0000: │ payout/protos/payout/gen/nestjs/team/youthink/payout/v1alpha1/payout.service.ts
➤ YN0000: │ 
➤ YN0000: │   Error: Merge conflict marker encountered.
➤ YN0000: │ 
➤ YN0000: │ 
➤ YN0000: └ Completed in 30s 261ms
➤ YN0000: Failed with errors in 30s 262ms

```

### Вопрос

Из-за чего это может быть и как пофиксить? Как я понимаю все конфликты на стороне бэка, допустим в format не написано в каком именно файле конфликт

**Comment by TFK70** [comment]
@brusselboy руками здесь ничего резолвить не нужно, просто прими все изменения касающиеся бэк as-it

В IDE ПКМ -> Git -> Resolve Conflicts -> Accept Theirs (или делай как самому удобнее)

format и typecheck падают из-за гитовых маркеров которые при конфликтах появляются, все будет норм когда конфликтов не будет

**Comment by brusselboy** [comment]
@TFK70 Как вызвать окно Resolve Conflicts? У кого то в тулбаре есть кнопка VCS в котором есть Git и там уже есть Resolve Conflicts, у меня её нету 

![image](https://user-images.githubusercontent.com/35490768/174280871-b7538323-3f15-42d9-8065-f5ad6440bb6b.png)

Во вкладке Git тоже нету Resolve Conflicts

**Comment by brusselboy** [comment]
## Баг с вёрсткой
@TFK70 

### Описание
Когда заходишь на страницу фрода дефолтно должна происходить фильтрация по подозрительной активности, это сделано, но когда страница загрузилась почему-то отрисовывается мобильная версия фильтров. 

Причина из-за которой происходит этот баг выявлена. Чтобы реализовать дефолтную фильтрацию нам нужно чтобы изначально был выбран данный [чекбокс](https://www.figma.com/file/ofuBEflZhwVbl3eGV9EXvv/Youthink-%7C-Back-Panel?node-id=324%3A16369) с сильной подозрительной активностью, библиотека downshift [предоставляет](https://www.downshift-js.com/use-multiple-selection#usage-with-select) такую возможность, в хуке `useMultipleSelection` можно объявить начальный стейт выделенных айтемов, что я и [сделал](https://github.com/YouThinkResearch/web/blob/feat/fraud-analytics-page/ui/select/src/select.component.tsx#L38-L39) в компоненте селекта, но из-за этого почему-то отрисовывается мобильная версия фильтров.

### Материалы
На видео видно, что когда страница загрузилась появляется мобильная версия фильтров, хотя она вообще никаким образом не может отрисовываться на десктопе - [код мобильной версии](https://github.com/YouThinkResearch/web/blob/feat/fraud-analytics-page/admin/fragments/fraud-analytics/src/filters/filters.component.tsx#L141-L186), есть `display={['flex', 'flex', 'none']}`, но всё равно отрисовывается.

Также ещё показал на видео, если перейти на другую страницу и вернутся обратно, баг пропадает.

https://user-images.githubusercontent.com/35490768/174296149-feece3c5-c9d0-4603-b031-aea9b3ef2b01.mp4

Бага нету если ничего не передавать в начальный стейт:

https://user-images.githubusercontent.com/35490768/174297250-a6088470-c46c-4f24-b207-f58e9337844a.mp4
