### ISSUE TITLE
Users

### ISSUE THREAD

**Issue by brusselboy** [atls-academy/brusselboy.github.io#13]
### С чем связан запрос на фичу?

ref -> [click](https://github.com/YouThinkResearch/web/issues/694)

Сделать страницу пользователей для бэк панели

[Дизайн](https://www.figma.com/file/ofuBEflZhwVbl3eGV9EXvv/Youthink-%7C-Back-Panel?node-id=320%3A11887)

### Расскажите как вы это себе видите

**Locations:**

- `admin/pages`
- `admin/fragments`

**Route:**

- `/users`

**Comment by TFK70** [comment]
Дело в [useEffect](https://github.com/YouThinkResearch/web/blob/feat/users-page/admin/fragments/users/src/user/edit-user/edit-user.component.tsx#L26). Он вызывается для **всех** элементов когда изменяется isUserEdit, и модалка, соответственно, открывается для всех

Если ты конкретизируешь триггер для модалки - все будет норм
