### ISSUE TITLE
Замена uri в dashboard

### ISSUE THREAD

**Issue by brusselboy** [atls-academy/brusselboy.github.io#6]
### Описание бага
@TFK70 
Не фетчатся данные с нового gateway
   
### Воспроизведение
Шаги для воспроизведения бага:
1. В файле [_app.tsx](https://github.com/YouThinkResearch/web/blob/feat/admin-page/dashboard/entrypoints/renderer/src/pages/_app.tsx#L29) меняем uri на: 'https://private-gateway.youthink.site/'
2. Запускаемся yarn workspace @dashboard/renderer-entrypoint dev
3. Нажимаем на иконку профиля в навигации, далее нажимаем Продолжить заполнение
4. Видим ошибку Unhandled Runtime Error Error: 14 UNAVAILABLE: no healthy upstream
![Снимок экрана от 2022-04-22 18-10-49](https://user-images.githubusercontent.com/35490768/164731573-c099a4a8-52c9-465e-b282-3ee7596857c1.png)

**Comment by brusselboy** [comment]
## Стилизация Input
@TFK70 

### Характер проблема
Проблема в стилизации + добавления элементов только для некоторых инпутов

### Описание

Имеется компонент [инпута](https://github.com/YouThinkResearch/web/blob/feat/admin-page/ui/input/src/input.component.tsx), мне нужно стилизовать его вот так:

![Снимок экрана от 2022-04-27 12-21-29](https://user-images.githubusercontent.com/35490768/165474516-e8c7e3ba-b9fa-439f-980a-5cc030e411cd.png)

Но если я буду изменять стили для [инпута Search](https://github.com/YouThinkResearch/web/blob/feat/admin-page/ui/input/src/input.component.tsx#L95), в таком случае я изменю стили для всех существующих инпутов на проекте.
Как мне стилизовать + добавлять какие-нибудь элементы в инпут, например крестик для очистки содержимого в инпуте или кнопку поиска, потому-что в каких-то инпутах есть эти элементы, в каких-то нету. И сделать это так, чтобы не изменялись все инпуты на проекте?

### Как решил вопрос со стилизацией на данный момент

Сейчас я делаю стилизацию инпутов следующим образом, в компоненте инпута [экспортирую стили](https://github.com/YouThinkResearch/web/blob/feat/admin-page/ui/input/src/input.component.tsx#L37) и уже нужный мне инпут [оборачиваю](https://github.com/YouThinkResearch/web/blob/feat/admin-page/admin/fragments/header/src/header.component.tsx#L60) для стилизации

**Comment by TFK70** [comment]
> ## Стилизация Input
> @TFK70
> 
> ### Характер проблемы
> Проблема в стилизации + добавления элементов только для некоторых инпутов
> 
> ### Описание
> Имеется компонент [инпута](https://github.com/YouThinkResearch/web/blob/feat/admin-page/ui/input/src/input.component.tsx), мне нужно стилизовать его вот так:
> 
> ![Снимок экрана от 2022-04-27 12-21-29](https://user-images.githubusercontent.com/35490768/165474516-e8c7e3ba-b9fa-439f-980a-5cc030e411cd.png)
> 
> Но если я буду изменять стили для [инпута Search](https://github.com/YouThinkResearch/web/blob/feat/admin-page/ui/input/src/input.component.tsx#L95), в таком случае я изменю стили для всех существующих инпутов на проекте. Как мне стилизовать + добавлять какие-нибудь элементы в инпут, например крестик для очистки содержимого в инпуте или кнопку поиска, потому-что в каких-то инпутах есть эти элементы, в каких-то нету. И сделать это так, чтобы не изменялись все инпуты на проекте?
> 
> ### Как решил вопрос со стилизацией на данный момент
> Сейчас я делаю стилизацию инпутов следующим образом, в компоненте инпута [экспортирую стили](https://github.com/YouThinkResearch/web/blob/feat/admin-page/ui/input/src/input.component.tsx#L37) и уже нужный мне инпут [оборачиваю](https://github.com/YouThinkResearch/web/blob/feat/admin-page/admin/fragments/header/src/header.component.tsx#L60) для стилизации

Если тебе нужно изменять форму/размеры инпута - тебе нужно создать новые shape styles и выбирать его через проп size

Если тебе нужна другая раскраска инпута - тебе нужны новые appearance styles и проп variant (если там такой есть вообще, если не ошибаюсь у всех инпутов раскраска одна)

Если тебе нужно обвесить инпут доп.компонентами - тебе нужны аддоны или аттачменты. Все примеры есть в uikit, я их уже кидал. Показывать/скрывать какой-либо элемент ты можешь через дополнительный проп

Более того кастомный крестик я уже реализовывал на визибле, что изначально было твоей задачей, так что тем более не понимаю что от меня здесь требуется - https://github.com/torin-asakura/VSBLE/tree/master/ui/input/src

**Comment by brusselboy** [comment]
## Баг с инпутом
@TFK70 

### Описание
При нажатии на любой из аттачментов они пропадают

https://user-images.githubusercontent.com/35490768/165591912-35ddd1a1-d6ce-4628-8326-fe16b3a16a29.mp4

К сожалению логов нету, так как я особо без понятия что нужно логать. Могу только предположить, что проблема в самом компоненте [инпута](https://github.com/YouThinkResearch/web/blob/feat/admin-page/ui/input/src/input.component.tsx) т.к сравнивал и стили и сами аттачменты всё идентично с визиблом, вообще в целом старался делать по аналогии, как это реализовано на визибле, в чём может быть проблема?

**Comment by TFK70** [comment]
@brusselboy 

Перестань во всем ссылаться на визибл, это просто один из многих проектов где используется инпут, если ты не понимаешь как работает инпут, но при этом тебе дико везет и копипаста продолжает магическим образом работать - от этого никому лучше не становится. Сейчас мы столкнулись с ситуацией когда копипаста не сработала, но вместо того чтобы сослаться на механизм работы инпута ты ссылаешься на то что "все как в визибле". Получается ты предлагаешь мне взять твой код, взять код из визибла, под лупой изучить обе реализации и предоставить тебе отчет о том, где ты недокопипастил?

**Comment by brusselboy** [comment]
## Отслеживание в фокусе инпут или нет
@TFK70 


[компонент поиска](https://github.com/YouThinkResearch/web/blob/feat/admin-page/admin/fragments/header/src/search/search.component.tsx)

Чтобы отрисовывать бэкдроп, нужно отслеживать в фокусе инпут или нет, для этого создал ref 

``` tsx
  const ref = useRef(null)
```

передал его в сам инпут 

``` tsx
<Input
  style={{paddingRight: '4px'}}
  placeholder={intl.formatMessage(messages.search)}
  type='search'
  colors='ghost'
  value={searchValue}
  onChange={setSearchValue}
  attachment={['cross', 'search']}
  ref={ref}
/>
```

и уже в Condition чтобы отрисовывать бэкдроп [делаю условие](https://github.com/YouThinkResearch/web/blob/feat/admin-page/admin/fragments/header/src/search/search.component.tsx#L47) в фокусе инпут или нет. Пока там временное условие. Как можно отслеживать в фокусе инпут или нет? В ref.current есть поле onfocus, я пытался через него отслеживать, но он всегда null и изменить не получается

**Comment by TFK70** [comment]
@brusselboy [бум](https://github.com/torin-asakura/VSBLE/blob/master/ui/input/src/input.component.tsx#L83)
