### ISSUE TITLE
Баги в dashboard

### ISSUE THREAD

**Issue by brusselboy** [atls-academy/brusselboy.github.io#8]
## Некорректное поведение лейеров и блюра
@TFK70 

[ref 8 пункт](https://github.com/YouThinkResearch/web/issues/669)
### Описание
Хедер не блюрился при нажатии на элементы в самом хедере, чтобы пофиксить на данный момент [приходится менять позиционирование хедера](https://github.com/YouThinkResearch/web/blob/fix/dashboard-styles/fragments/navigation/src/navigation.component.tsx#L86), т.к при параметре 'sticky' блюр не работает. При стики zIndex тоже не помогает, изначально была идея задать каждому элементу в хедере zIndex больше чем у popover, по этому меняю position изначально он sticky, а при нажатии на элементы становится relative
   
### Воспроизведение
Шаги для воспроизведения бага:
1. Запускаемся @dashboard/renderer-entrypoint dev 
2. Нажимаем на любой элемент в хедере который открывает popover
3. Видим что теперь блюр закрашивает хедер, но если проскроллить вниз кнопки становятся не кликабельные

### Ожидаемое поведение
При скролле вниз кликабельные элементы в хедере

### Материалы
https://user-images.githubusercontent.com/35490768/167117995-a9e80d97-1b9b-45b2-ab88-024ff39e0b49.mp4

## Footer и пустое пространство над ним
[ref 2 пункт](https://github.com/YouThinkResearch/web/issues/669)

### Описание 
Пустое пространство появлялось из-за заданного параметра height='100vh' у компонента [dashboard-actual-surveys](https://github.com/YouThinkResearch/web/commit/f776744d2e96e53e109f8e5305d9f2e76f7074e5#diff-bdef6492843ab80e14ba265e437aa89f179a192f7cc3e02b8b037a41ca800d88L26) это компонент с опросами:
<details>

![image](https://user-images.githubusercontent.com/35490768/167119717-22fc40f2-eb2e-467e-b605-6e25fd8d0685.png)

</details>

 и у компонента [сайдбара](https://github.com/YouThinkResearch/web/commit/f776744d2e96e53e109f8e5305d9f2e76f7074e5#diff-e92f1b2a6230597168d3362486ecdee11cc311f81f190ee2117e4ef44b6f1f51L24)

<details>

![image](https://user-images.githubusercontent.com/35490768/167120182-98d0aab8-06a8-499d-9988-4fb1c40df2f9.png)

</details>

Сейчас высоту поменял с 100vh на 100% и пустого пространства нету, но теперь при скейлинге футер подтягивается вверх и оставляет под собой пустое пространство.

### Воспроизведение
Шаги для воспроизведения бага:
1. Запускаемся @dashboard/renderer-entrypoint dev 
2. Скейлимся (ctrl -)
3. Видим что футер подтягивается вверх и оставляет снизу пустое пространство

https://user-images.githubusercontent.com/35490768/167120994-1b97dc8b-bc3b-49bc-ba3d-ec0f7cc718b2.mp4

### Ожидаемое поведение
Ни над футером ни под ним не было пустого пространства

### Второе возможное решение проблемы
Задать футеру position=absolute и bottom=0, в таком случае пустого пространства снизу не будет, но теперь он будет налезать на контент сверху:
 
https://user-images.githubusercontent.com/35490768/167121546-cd233522-1277-4286-b1e7-dab3693a5fcc.mp4

## Рубли надо рендерить отдельным шрифтом (Rouble PT Sans)
[ref 10 пункт](https://github.com/YouThinkResearch/web/issues/669) 

Здесь хотелось бы поподробнее узнать, как эту проблему решить, так как на данный момент используется компонент [Currency](https://github.com/YouThinkResearch/web/blob/fix/dashboard-styles/fragments/navigation/src/balance/balance.component.tsx#L29-L35) у которого есть пропс currency в котором указывается название валюты, то есть там не только рубль. Подойдет ли здесь шрифт Rouble PT Sans? как я понял этот шрифт заточен только под рубль

**Comment by TFK70** [comment]
@brusselboy 

1. Если я все правильно понял - то ты хочешь блюрить хедер? В дизайне он не блюрится, я тогда не совсем понимаю что ты там собираешься делать
2. Не растягивай футер на 100%. Задай ему ширину в пикселях из дизайна, точно не делай ему абсолют, футер не должен быть стики/фиксед или еще что-то. Попробуй на гитхабе заскейлить футер - у тебя должно быть так же
3. Если внимательно посмотришь на Currency, то увидишь что его база - тот же Text со всеми сопутствующими пропами. В ui никаких изменений делать не надо, ты можешь просто указать fontFamily по месту использования:

```javascript
<Currency 
   amount={10}
   fontFamily='rouble'
/>
```

**Comment by brusselboy** [comment]
@TFK70 

> 1. Если я все правильно понял - то ты хочешь блюрить хедер? В дизайне он не блюрится, я тогда не совсем понимаю что ты там собираешься делать

Я сначала тоже не совсем понял про что имеется ввиду в 8 пункте про блюр у меня моник с TN матрицей чтоб понять про что идёт речь и увидеть разницу пришлось головой вверх внизу вертеть, так как там это еле заметно, но там говорится как раз про то что я делаю. Там есть вот эта полу заметная граница между хедером и остальным контентом который блюрится:

С блюром хедера:
![image](https://user-images.githubusercontent.com/35490768/167125350-421445ed-72fc-4ab6-bb2e-12cb6c27fe32.png)

Без блюра хедера (смотреть строго на пересечение между хедером и контентом ниже):

![image](https://user-images.githubusercontent.com/35490768/167125584-aa4dbdb1-77c9-4adf-ae6f-416ed225e6ec.png)

**Comment by TFK70** [comment]
@brusselboy тогда проблема в zIndex, он если что не просто так там был выставлен

Скорее всего, когда ты скроллишь до итема опроса и нажимаешь на хедер - твой клик регистрируется не как клик по хедеру, а как клик по итему, поэтому ничего не происходит

Я вижу здесь 2 варианта:

1. Попробовать добиться желаемого эффекта с помощью `box-shadow`
2. Контейнерам всех активных элементов в хедере менять zIndex на больший

**Comment by TFK70** [comment]
@brusselboy 

> p.s также ты написал:
В ui никаких изменений делать не надо
что ставит под сомнение все действия которые я делаю, мб я вообще не в ту сторону думаю

Я имел ввиду чтобы не в ui/text не лез и Currency не шатал, шрифты тебе так и так через тему надо загружать

**Comment by brusselboy** [comment]
## Не подключается шрифт
@TFK70 
### Описание
1. Делаю инжект шрифта, но из-за [require](https://github.com/YouThinkResearch/web/blob/fix/dashboard-styles/ui/theme/src/inject-fonts.ts#L19) приложение падает с ошибкой.
2. Беда номер два которая произойдет, когда ошибка будет пофикшена, подключил шрифт на прямую через font-face в [глобальных стилях](https://github.com/YouThinkResearch/web/blob/fix/dashboard-styles/ui/theme/src/global.styles.tsx) просто чтобы посмотреть как будет работать и тут самоё интересное, что меняется не сам символ рубля, а меняется только число. Это по сути и логично, так как шрифт не содержит в себе цифр, онли знак рубля.

Здесь просто добавляю fontFamily
```tsx
<Currency
  color='black'
  fontWeight='medium'
  fontSize='default'
  fontFamily='rouble'
  currency='RUB'
  amount={money}
/>
```

Наглядно:
![image](https://user-images.githubusercontent.com/35490768/167215038-169980db-c564-48e5-9cf7-7f037d999166.png)

### Воспроизведение
Шаги для воспроизведения ошибки:
1. Запускаемся @dashboard/renderer-entrypoint dev
2. Ловим ошибку при компиляции

### Ожидаемое поведение
Замена шрифта только у символа рубля


### Лог ошибки
```
error - ../../../../.yarn/__virtual__/@ui-theme-virtual-b02a7d65f1/1/ui/theme/fonts/Inter-Black.woff
Module parse failed: Unexpected character '' (1:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
```

**Comment by TFK70** [comment]
@brusselboy 

1. Совсем забыл что для рубля используется отдельный компонент в ui/text, так что поменяй fontFamily ему
2. `yarn workspace @dashboard/renderer-entrypoint add -D next-fonts@1.0.3` и скопипасти это в `next.config.js`:

```javascript
const withPlugins = require('next-compose-plugins')
const withFonts = requrie('next-fonts')

const nextConfig = {
  experimental: {
    externalDir: true,
    swcFileReading: false,
    workerThreads: true,
    esmExternals: 'loose',
    outputStandalone: true,
  },
}

module.exports = withPlugins([withFonts], nextConfig)
```
